kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-client-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: aria-on-kubernetes
    spec:
      containers:
        - name: aria2
          image: 
          volumeMounts:
            - name: download
              mountPath: /persistentvolumes
      volumes:
        - name: download
          persistentVolumeClaim:
            claimName: aria2-claim